#!/bin/sh
# Created from belcarra-acm-eem.json

mkdir -p "/sys/kernel/config/usb_gadget/belcarra-acm-eem"
echo "0x15ec" > "/sys/kernel/config/usb_gadget/belcarra-acm-eem/idVendor"
echo "0xf102" > "/sys/kernel/config/usb_gadget/belcarra-acm-eem/idProduct"
echo "0x0001" > "/sys/kernel/config/usb_gadget/belcarra-acm-eem/bcdDevice"
echo "0x00" > "/sys/kernel/config/usb_gadget/belcarra-acm-eem/bDeviceClass"
echo "0x00" > "/sys/kernel/config/usb_gadget/belcarra-acm-eem/bDeviceSubClass"
echo "0x00" > "/sys/kernel/config/usb_gadget/belcarra-acm-eem/bDeviceProtocol"
echo "0x0200" > "/sys/kernel/config/usb_gadget/belcarra-acm-eem/bcdUSB"
echo "0x40" > "/sys/kernel/config/usb_gadget/belcarra-acm-eem/bMaxPacketSize0"
mkdir -p "/sys/kernel/config/usb_gadget/belcarra-acm-eem/strings/0x409"
echo "0123456789" > "/sys/kernel/config/usb_gadget/belcarra-acm-eem/strings/0x409/serialnumber"
echo "ACMx2-EEM Gadget" > "/sys/kernel/config/usb_gadget/belcarra-acm-eem/strings/0x409/product"
echo "Belcarra Technologies Corp" > "/sys/kernel/config/usb_gadget/belcarra-acm-eem/strings/0x409/manufacturer"
mkdir -p "/sys/kernel/config/usb_gadget/belcarra-acm-eem/functions/acm.GS0"
mkdir -p "/sys/kernel/config/usb_gadget/belcarra-acm-eem/functions/acm.GS1"
mkdir -p "/sys/kernel/config/usb_gadget/belcarra-acm-eem/functions/eem.usb0"
echo "5" > "/sys/kernel/config/usb_gadget/belcarra-acm-eem/functions/eem.usb0/qmult"
echo "c6:34:7c:45:a6:c5" > "/sys/kernel/config/usb_gadget/belcarra-acm-eem/functions/eem.usb0/host_addr"
echo "0e:6a:8a:85:db:76" > "/sys/kernel/config/usb_gadget/belcarra-acm-eem/functions/eem.usb0/dev_addr"
mkdir -p "/sys/kernel/config/usb_gadget/belcarra-acm-eem/configs/config.1"
echo "0x80" > "/sys/kernel/config/usb_gadget/belcarra-acm-eem/configs/config.1/bmAttributes"
echo "2" > "/sys/kernel/config/usb_gadget/belcarra-acm-eem/configs/config.1/MaxPower"
mkdir -p "/sys/kernel/config/usb_gadget/belcarra-acm-eem/configs/config.1/strings/0x409"
echo "CDC 2xACM+EEM" > "/sys/kernel/config/usb_gadget/belcarra-acm-eem/configs/config.1/strings/0x409/configuration"
ln -s "/sys/kernel/config/usb_gadget/belcarra-acm-eem/functions/acm.GS0" "/sys/kernel/config/usb_gadget/belcarra-acm-eem/configs/config.1/acm.GS0"
ln -s "/sys/kernel/config/usb_gadget/belcarra-acm-eem/functions/eem.usb0" "/sys/kernel/config/usb_gadget/belcarra-acm-eem/configs/config.1/eem.usb0"
ln -s "/sys/kernel/config/usb_gadget/belcarra-acm-eem/functions/acm.GS1" "/sys/kernel/config/usb_gadget/belcarra-acm-eem/configs/config.1/acm.GS1"

basename /sys/class/udc/* > /sys/kernel/config/usb_gadget/belcarra-acm-eem/UDC
